name: Debricked scan

on: [push]

jobs:
  vulnerabilities-scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install Debricked CLI
        run: |
          curl -L https://github.com/debricked/cli/releases/latest/download/cli_linux_x86_64.tar.gz | tar -xz debricked
          ./debricked --version

      # Here I make two separate scans with debricked in different parts of the repo
      # This will create two separate repos in the debricked tool, and can be managed
      # with different policies etc. 
      # You can also split these out to two separate actions to make the results easier to consume visually. 
      - name: Run Scan
        run: |
          ./debricked scan api/ -r api-service
          ./debricked scan web/ -r web-service
        env:
          DEBRICKED_TOKEN: ${{ secrets.DEBRICKED_TOKEN }}
        
        
